name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      run: xcodebuild clean test -project "DemoVSee.xcodeproj" -scheme "DemoVSee" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
